# Generated by Django 2.2.3 on 2020-05-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_cleandev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleanDev',
        ),
    ]
