# Generated by Django 2.2.3 on 2020-05-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_cleandev'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_projects',
            fields=[
                ('frontend', models.CharField(blank=True, max_length=15, primary_key=True, serialize=False)),
                ('projid', models.CharField(blank=True, max_length=50, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'latest_projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr12_18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr12_18',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr1_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr1_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr26_40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr26_40',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr2_3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr2_3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr40_52',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr40_52',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr4_6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr4_6',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr68_92',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr68_92',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rcvr8_10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'Rcvr8_10',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RcvrArray18_26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'RcvrArray18_26',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RcvrArray75_115',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'RcvrArray75_115',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RcvrMBA1_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_mhz', models.DecimalField(blank=True, db_column='Frequency_MHz', decimal_places=4, max_digits=12, null=True)),
                ('mjd', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'RcvrMBA1_2',
                'managed': False,
            },
        ),
    ]
